# Generated by Django 3.0.8 on 2020-08-18 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(help_text='Format: YYYY-MM-DD')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unsure')], max_length=1)),
                ('email', models.EmailField(help_text='Required. Enter a valid email address.', max_length=254)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('weight', models.IntegerField(help_text='Input weight in terms of kilograms.')),
                ('job', models.CharField(choices=[('AGRICULTURE', 'Agriculture, Food and Natural Resources'), ('CONSTRUCTION', 'Architecture and Construction'), ('ARTS', 'Arts, Audio/Video Technology and Communication'), ('BUSINESS', 'Business Management and Administration'), ('EDUCATION', 'Education and Training'), ('FINANCE', 'Finance'), ('GOV', 'Government and Public Administration'), ('HEALTH', 'Health Sciences'), ('TOURISM', 'Hospitality and Tourism'), ('HUMAN_SERVICES', 'Human Services'), ('IT', 'Information Technology'), ('LAW', 'Law, Public Safety, Corrections and Security'), ('MANUFACTURING', 'Manufacturing'), ('MARKETING', 'Marketing, Sales and Service')], max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
