# Generated by Django 3.0.8 on 2020-08-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_activity_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
    ]
