# Generated by Django 3.0.8 on 2020-08-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_payment_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date'], 'verbose_name_plural': 'activities'},
        ),
    ]
