# Generated by Django 3.0.8 on 2020-08-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200820_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='portfolio',
            field=models.CharField(choices=[('CASH', 'Cash'), ('HEALTH_TECH', 'Health Tech Fund'), ('ESG', 'Sustainability Fund'), ('COMBINED', 'Combined Health and Sustainability Fund')], default='CASH', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='portfolio',
            field=models.CharField(choices=[('CASH', 'Cash'), ('HEALTH_TECH', 'Health Tech Fund'), ('ESG', 'Sustainability Fund'), ('COMBINED', 'Combined Health and Sustainability Fund')], default='CASH', max_length=100),
        ),
    ]
