# Generated by Django 3.0.8 on 2020-08-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_withdrawal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='portfolio',
            field=models.CharField(choices=[('CASH', 'Cash'), ('HEALTH_TECH', 'Health Tech Fund'), ('ESG', 'Sustainability Fund')], default='CASH', max_length=100),
        ),
    ]
