# Generated by Django 3.0.8 on 2020-08-31 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20200825_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weekly_hours_of_exercise',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Use format: HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Use format: HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='portfolio',
            field=models.CharField(choices=[('CASH', 'Cash'), ('HEALTH_TECH', 'Health Tech Fund'), ('ESG', 'Sustainability Fund')], default='CASH', max_length=100),
        ),
    ]
