# Generated by Django 3.0.8 on 2020-10-01 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20201001_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
